using Interfaces;
using Interfaces.ContinuousEffects;

namespace Abilities;

/// <summary>
/// 604.1.
/// Static abilities do something all the time rather than being activated or
/// triggered. They are written as statements, and they’re simply true.
/// </summary>
public class StaticAbility : Ability, IStaticAbility
{
    private readonly List<IContinuousEffect> _continuousEffects = [];

    /// <summary>
    /// 604.2.
    /// Static abilities create continuous effects, some of which are prevention
    /// effects or replacement effects.
    /// </summary>
    public IEnumerable<IContinuousEffect> ContinuousEffects =>
        _continuousEffects;

    /// <summary>
    /// 604.2.
    /// Effects generated by the static ability are active as long as the card
    /// with the ability remains on the battle zone and has the ability,
    /// or as long as the card with the ability remains in the appropriate zone.
    /// </summary>
    public ZoneType FunctionZone { get; set; } = ZoneType.BattleZone;

    public StaticAbility() : base()
    {
    }

    public StaticAbility(IContinuousEffect continuousEffect) : base()
    {
        _continuousEffects.Add(continuousEffect);
    }

    protected StaticAbility(StaticAbility ability) : base(ability)
    {
        _continuousEffects = [.. ability._continuousEffects.Select(
            x => x.Copy())];
        FunctionZone = ability.FunctionZone;
    }

    public override IAbility Copy()
    {
        return new StaticAbility(this);
    }

    public sealed override string ToString()
    {
        return string.Join(" ", _continuousEffects.Select(
            x => UpperCaseFirstCharacter(x.ToString())));
    }

    public override bool Equals(object? obj)
    {
        if (!base.Equals(obj)) return false;
        if (obj is not StaticAbility ability) return false;
        if (!_continuousEffects.SequenceEqual(
            ability._continuousEffects)) return false;
        return true;
    }

    public override int GetHashCode()
    {
        var hash = new HashCode();
        hash.Add(base.GetHashCode());
        foreach (var effect in _continuousEffects)
        {
            hash.Add(effect);
        }
        return hash.ToHashCode();
    }
}
