namespace DuelMastersModels.Effects.Periods
{
    /// <summary>
    /// A continuous effect generated by the resolution of a spell or ability lasts as long as stated by the spell or ability creating it (such as “until end of turn”). If no duration is stated, it lasts until the end of the game.
    /// </summary>
    public abstract class Period : ICopyable<Period>
    {
        public abstract Period Copy();
    }

    internal class Once : Period
    {
        public override Period Copy()
        {
            return new Once();
        }
    }
}
