namespace Interfaces.ContinuousEffects;

public interface IContinuousEffect : IEffect
{
    /// <summary>
    /// 613.7a A continuous effect generated by a static ability has
    /// the same timestamp as the object the static ability is on, or
    /// the timestamp of the effect that created the ability,
    /// whichever is later.
    /// If the effect that created the ability has the later
    /// timestamp and the object the ability is on receives a new
    /// timestamp, each continuous effect generated by static
    /// abilities of that object receives a new timestamp as well,
    /// but the relative order of those timestamps remains the same.
    /// </summary>
    int Timestamp { get; set; }
    IContinuousEffect Copy();
}
