//------------------------------------------------------------------------------
// <auto-generated>
//     Työkalu muodosti tämän koodin.
//     Suorituksenaikainen versio:4.0.30319.42000
//
//     Tähän tiedostoon tehdyt muutokset saattavat aiheuttaa virheellistä toimintaa. Ne menetetään, jos
//     koodi muodostetaan uudelleen.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class cards {
    
    private creature[] creatureField;
    
    private spell[] spellField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("creature", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public creature[] creature {
        get {
            return this.creatureField;
        }
        set {
            this.creatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("spell", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public spell[] spell {
        get {
            return this.spellField;
        }
        set {
            this.spellField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class creature : card {
    
    private race[] racesField;
    
    private string powerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public race[] races {
        get {
            return this.racesField;
        }
        set {
            this.racesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string power {
        get {
            return this.powerField;
        }
        set {
            this.powerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum race {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Angel Command")]
    AngelCommand,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Liquid People")]
    LiquidPeople,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(spell))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(creature))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class card {
    
    private civilization[] civilizationsField;
    
    private ability[] abilitiesField;
    
    private string nameField;
    
    private string costField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public civilization[] civilizations {
        get {
            return this.civilizationsField;
        }
        set {
            this.civilizationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ability[] abilities {
        get {
            return this.abilitiesField;
        }
        set {
            this.abilitiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string cost {
        get {
            return this.costField;
        }
        set {
            this.costField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum civilization {
    
    /// <remarks/>
    Light,
    
    /// <remarks/>
    Water,
    
    /// <remarks/>
    Darkness,
    
    /// <remarks/>
    Fire,
    
    /// <remarks/>
    Nature,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ability {
    
    private string param1Field;
    
    private trigger triggerField;
    
    private bool triggerFieldSpecified;
    
    private effect effectField;
    
    private abilityType typeField;
    
    public ability() {
        this.typeField = abilityType.normal;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string param1 {
        get {
            return this.param1Field;
        }
        set {
            this.param1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public trigger trigger {
        get {
            return this.triggerField;
        }
        set {
            this.triggerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool triggerSpecified {
        get {
            return this.triggerFieldSpecified;
        }
        set {
            this.triggerFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public effect effect {
        get {
            return this.effectField;
        }
        set {
            this.effectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(abilityType.normal)]
    public abilityType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum trigger {
    
    /// <remarks/>
    none,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("When you put this creature into the battle zone")]
    Whenyouputthiscreatureintothebattlezone,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum effect {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Each of your creatures in the battle zone gets power attacker +$1 until the end o" +
        "f the turn.")]
    Eachofyourcreaturesinthebattlezonegetspowerattacker1untiltheendoftheturn,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Each of your other creatures in battle zone gets +$1 power and has blocker and do" +
        "uble breaker.")]
    Eachofyourothercreaturesinbattlezonegets1powerandhasblockeranddoublebreaker,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("You may draw a card.")]
    Youmaydrawacard,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum abilityType {
    
    /// <remarks/>
    normal,
    
    /// <remarks/>
    survivor,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("turbo rush")]
    turborush,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("silent skill")]
    silentskill,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("wave striker")]
    wavestriker,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class spell : card {
}
