using Cards.Cards.DM10;
using Xunit;

namespace TestCards.Cards.DM10;

public class VanillaTests
{
    [Fact]
    public void CreateCards()
    {
        // Arrange + Act + Assert
        _ = new AdventureBoar();
        _ = new AncientHornTheWatcher();
        _ = new AquaSkydiver();
        _ = new AquaStrummer();
        _ = new ArdentLunatron();
        _ = new ArmoredRaiderGandaval();
        _ = new BalzaSeekerOfHyperpearls();
        _ = new BatteryCluster();
        _ = new BenzoTheHiddenFury();
        _ = new BerochikaChannelerOfSuns();
        _ = new BodaciousGiant();
        _ = new BombazarDragonOfDestiny();
        _ = new BradSuperKickinDynamo();
        _ = new BubbleScarab();
        _ = new BulglufTheSpydroid();
        _ = new BuoyantBlowfish();
        _ = new BurnwispLizard();
        _ = new CarnivalTotem();
        _ = new ChargeWhipper();
        _ = new ClearloGraceEnforcer();
        _ = new ColossusBoost();
        _ = new CoreCrashLizard();
        _ = new Cragsaur();
        _ = new CrystalSpinslicer();
        _ = new DedreenTheHiddenCorrupter();
        _ = new DeklowazTheTerminator();
        _ = new DolmarksTheShadowWarrior();
        _ = new EarthRipperTalonOfRage();
        _ = new ElixiaPurebladeElemental();
        _ = new EstolVizierOfAqua();
        _ = new ExplosiveTrooperZalmez();
        _ = new FerrosaturnSpectralKnight();
        _ = new FlohdaniTheSpydroid();
        _ = new FluorogillManta();
        _ = new ForcedFrenzy();
        _ = new GajirabuteVileCenturion();
        _ = new GalekTheShadowWarrior();
        _ = new GaulezalDragon();
        _ = new Gigamente();
        _ = new Gigandura();
        _ = new GlaisMejiculaTheExtreme();
        _ = new GontaTheWarriorSavage();
        _ = new HawkeyeLunatron();
        _ = new HourglassMutant();
        _ = new Hurlosaur();
        _ = new HurricaneCrawler();
        _ = new HustleBerry();
        _ = new IkazTheSpydroid();
        _ = new InfernalCommand();
        _ = new JigglyTotem();
        _ = new KaemiraTheOracle();
        _ = new KaratePotato();
        _ = new KejilaTheHiddenHorror();
        _ = new KingOquanos();
        _ = new LegacyShell();
        _ = new LemikVizierOfThought();
        _ = new LukiaLexPinnacleGuardian();
        _ = new MelniaTheAquaShadow();
        _ = new MessaBahnaExpanseGuardian();
        _ = new MezgerCommandoLeader();
        _ = new MikayRattlingDoll();
        _ = new Milporo();
        _ = new MinelordSkyterror();
        _ = new MummyWrapShadowOfFatigue();
        _ = new MykeesPliers();
        _ = new MysticMagician();
        _ = new NecrodragonBryzenaga();
        _ = new NightmareInvader();
        _ = new PalaOlesisMorningGuardian();
        _ = new PierrPsychoDoll();
        _ = new PinpointLunatron();
        _ = new PointaTheAquaShadow();
        _ = new PoltalesterTheSpydroid();
        _ = new RapidReincarnation();
        _ = new RyudmilaChannelerOfSuns();
        _ = new SabermaskScarab();
        _ = new SanfistTheSavageVizier();
        _ = new ScowlingTomato();
        _ = new ShamanBroccoli();
        _ = new SiegeRollerBagash();
        _ = new SirenConcerto();
        _ = new SkyswordTheSavageVizier();
        _ = new SmashWarriorStagrandu();
        _ = new SoderlightTheColdBlade();
        _ = new Soulswap();
        _ = new SparkChemistShadowOfWhim();
        _ = new SpinalParasite();
        _ = new SporeblastErengi();
        _ = new StaticWarp();
        _ = new SupersonicJetPack();
        _ = new TagtappTheRetaliator();
        _ = new TajimalVizierOfAqua();
        _ = new TanzanyteTheAwakener();
        _ = new TauntingSkyterror();
        _ = new TechnoTotem();
        _ = new TerradragonCusdalf();
        _ = new TerradragonDakmaBalgarow();
        _ = new ThirstForTheHunt();
        _ = new TidePatroller();
        _ = new TorpedoCluster();
        _ = new TulkTheOracle();
        _ = new TwitchHornTheAggressor();
        _ = new UlexTheDauntless();
        _ = new UliyaTheEntrancer();
        _ = new UltimateDragon();
        _ = new Upheaval();
        _ = new VenomCapsule();
        _ = new VorgsEngine();
        _ = new WindAxeTheWarriorSavage();
        _ = new Zaltan();
        _ = new ZeroNemesisShadowOfPanic();
    }
}