using System;

namespace DuelMastersModels.Durations
{
    /// <summary>
    /// A continuous effect generated by the resolution of a spell or ability lasts as long as stated by the spell or ability creating it (such as “until end of turn”). If no duration is stated, it lasts until the end of the game.
    /// </summary>
    public abstract class Duration : ICopyable<Duration>, IDisposable
    {
        public abstract Duration Copy();

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        protected virtual void Dispose(bool disposing)
        {
            if (disposing)
            {
            }
        }
    }

    public class Once : Duration
    {
        public override Duration Copy()
        {
            return new Once();
        }
    }
}
